services:
  dbperformancecomparison:
    image: ${DOCKER_REGISTRY-}dbperformancecomparison
    build:
      context: .
      dockerfile: DbPerformanceComparison/Dockerfile
    environment:
      - POSTGRES__HOST=postgres
      - POSTGRES__PORT=5432
      - POSTGRES__DATABASE=db_performance_comparison
      - POSTGRES__USERNAME=myuser
      - POSTGRES__PASSWORD=mypassword
    depends_on:
      - postgres
      - mongodb
    ports:
      - "80:80"
    volumes:
      - ./output:/app/output

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db_performance_comparison
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
